[project]
name = "youzube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.2",
    "django-browser-reload>=1.21.0",
    "imagekitio>=5.2.0",
    "python-dotenv>=1.2.1",
]
